name: core
description: Main part of quizland calculator. Independed from any platform
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  auto_injector: ^2.0.5
  go_router: ^14.3.0
  go_router_paths: ^0.2.2
  animated_theme_switcher: ^2.0.10

  math_expressions: ^2.4.0
  local_hero:
    path: ../third_part_library/local_hero
  repository:
    path: ../repository
  flutter_constraintlayout: ^1.7.0-stable
  simple_animations: ^5.0.2
  flutter_layout_grid: ^2.0.7
  flutter_bloc: ^8.1.6
  conditional_wrap: ^3.0.0
  typethis: ^1.0.2
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  video_player: ^2.9.2
  auto_size_text: ^3.0.0
  widget_circular_animator: ^1.0.0
  just_audio_background: ^0.0.1-beta.13
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  asset_fill: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/harry_potter/
    - assets/harry_potter/question/
    - assets/harry_potter/question/a/
    - assets/harry_potter/question/o/
    - assets/harry_potter/question/q/
    - assets/harry_potter/question/u/
  fonts:
    - family: Harry
      fonts:
        - asset: assets/harry_potter.ttf